base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "WinstonLiyte"
repo_name: "daily_quant_paper"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
paper_list_json_path: './docs/quant-scholar.json'
paper_list_path: 'README.md'

keywords:
    "Machine Learning in Finance":
        filters: ["Machine Learning in Finance", "Statistical Finance"]
    "Deep Learning in Finance":
        filters: ["Deep Learning in Finance", "Computational Engineering, Finance, and Science"]
    "Reinforcement Learning in Finance":
        filters: ["Reinforcement Learning in Finance"]
    "Time Series Forecasting":
        filters: ["Time Series Forecasting"]
